In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_excel('Churn_Modelling.xlsx')

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
# Lets drop the unwwanted column.
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [7]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le = LabelEncoder()
df['Geography'] = le.fit_transform(df['Geography'])

In [10]:
le2 = LabelEncoder()
df['Gender'] = le2.fit_transform(df['Gender'])

In [11]:
df

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       0   42       2       0.00              1   
1             608          2       0   41       1   83807.86              1   
2             502          0       0   42       8  159660.80              3   
3             699          0       0   39       1       0.00              2   
4             850          2       0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          1       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [12]:
# Separating the Data into X and Y.
x = df.iloc[:,:-1]
x

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       0   42       2       0.00              1   
1             608          2       0   41       1   83807.86              1   
2             502          0       0   42       8  159660.80              3   
3             699          0       0   39       1       0.00              2   
4             850          2       0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          1       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [13]:
y = df.iloc[:,-1]
y 

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [14]:
# Will performing deep learning model will always perform Scaling 
from sklearn.preprocessing import StandardScaler

# Create object of the class
sc = StandardScaler()

# Scaling the X Variavle which include Input Features 
# Remember we dont scale the output Variable
x = sc.fit_transform(x)

In [15]:
x

array([[-0.32622142, -0.90188624, -1.09598752, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-0.44003595,  1.51506738, -1.09598752, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-1.53679418, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.60498839, -0.90188624, -1.09598752, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.25683526,  0.30659057,  0.91241915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 1.46377078, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [16]:
y = df['Exited'].values
y 

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [17]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size = 0.30, random_state = 1)


In [18]:
# from here we start building Neural Network

import tensorflow as tf
from tensorflow.keras import Sequential # it is Used to build NN
from tensorflow.keras.layers import Dense # it is used to add layers
from sklearn.metrics import classification_report # Evaluation 

In [19]:
# Building Neural Network

# Step 1 : initiate a model

ann = Sequential()

# Step 2: Add Layers to model 

ann.add(Dense(units = 12,activation = 'relu')) # Hidden Layers
ann.add(Dense(units = 1, activation = 'sigmoid')) # Output Layer

# step 3: Establishing connection with layers
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# step 4: fit the model
ann.fit(xtrain,ytrain,epochs = 100, batch_size = 32)

# Step 5: make predictions
ypred = ann.predict(xtest)

Epoch 1/100
219/219 [==============================] - 1s 1ms/step - loss: 0.6412 - accuracy: 0.6330
Epoch 2/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4870 - accuracy: 0.8030
Epoch 3/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4433 - accuracy: 0.8119
Epoch 4/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4251 - accuracy: 0.8189
Epoch 5/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4138 - accuracy: 0.8237
Epoch 6/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4044 - accuracy: 0.8293
Epoch 7/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3954 - accuracy: 0.8364
Epoch 8/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3869 - accuracy: 0.8391
Epoch 9/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3798 - accuracy: 0.8429
Epoch 10/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3734 - accura

219/219 [==============================] - 0s 1ms/step - loss: 0.3332 - accuracy: 0.8634
Epoch 82/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8634
Epoch 83/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8633
Epoch 84/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8630
Epoch 85/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8631
Epoch 86/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3324 - accuracy: 0.8636
Epoch 87/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3323 - accuracy: 0.8643
Epoch 88/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3324 - accuracy: 0.8623
Epoch 89/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3322 - accuracy: 0.8636
Epoch 90/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3321 - accuracy: 

In [20]:
ypred 

array([[0.0455858 ],
       [0.05752124],
       [0.05585487],
       ...,
       [0.02945778],
       [0.09925408],
       [0.06920675]], dtype=float32)

In [21]:
# step 6: Set the Threshold Value 

ypred = np.where(ypred>0.5,1,0)
ypred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [23]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      2373
           1       0.79      0.46      0.58       627

    accuracy                           0.86      3000
   macro avg       0.83      0.71      0.75      3000
weighted avg       0.85      0.86      0.85      3000

