In [29]:
#Importing Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [30]:
df = pd.read_csv("diabetes.csv")

In [31]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [32]:
# First check null entries
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [33]:
df.columns[df.isnull().any()]

Index([], dtype='object')

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [35]:
#Now, check for duplicate rows
df.drop_duplicates(inplace=True)
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

### REplace Zero with Mean

In [36]:
df['SkinThickness'].replace(0,df['SkinThickness'].mean(), inplace=True)

In [37]:
df['BloodPressure'].replace(0,df['BloodPressure'].mean(), inplace=True)

In [38]:
df['Glucose'].replace(0,df['Glucose'].mean(), inplace=True)

In [39]:
df['Insulin'].replace(0,df['Insulin'].mean(), inplace=True)

In [40]:
df['BMI'].replace(0,df['BMI'].mean(), inplace=True)

In [41]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0              6    148.0           72.0      35.000000   79.799479  33.6   
1              1     85.0           66.0      29.000000   79.799479  26.6   
2              8    183.0           64.0      20.536458   79.799479  23.3   
3              1     89.0           66.0      23.000000   94.000000  28.1   
4              0    137.0           40.0      35.000000  168.000000  43.1   
..           ...      ...            ...            ...         ...   ...   
763           10    101.0           76.0      48.000000  180.000000  32.9   
764            2    122.0           70.0      27.000000   79.799479  36.8   
765            5    121.0           72.0      23.000000  112.000000  26.2   
766            1    126.0           60.0      20.536458   79.799479  30.1   
767            1     93.0           70.0      31.000000   79.799479  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [42]:
df.values

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [43]:
x = df.drop(columns=["Outcome"])

In [44]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0              6    148.0           72.0      35.000000   79.799479  33.6   
1              1     85.0           66.0      29.000000   79.799479  26.6   
2              8    183.0           64.0      20.536458   79.799479  23.3   
3              1     89.0           66.0      23.000000   94.000000  28.1   
4              0    137.0           40.0      35.000000  168.000000  43.1   
..           ...      ...            ...            ...         ...   ...   
763           10    101.0           76.0      48.000000  180.000000  32.9   
764            2    122.0           70.0      27.000000   79.799479  36.8   
765            5    121.0           72.0      23.000000  112.000000  26.2   
766            1    126.0           60.0      20.536458   79.799479  30.1   
767            1     93.0           70.0      31.000000   79.799479  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [45]:
#Use the StandardScaler to scale the data set
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x =sc.fit_transform(x)

In [46]:
x

array([[ 0.63994726,  0.86527574, -0.0210444 , ...,  0.16725546,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.20598931, -0.51658286, ..., -0.85153454,
        -0.36506078, -0.19067191],
       [ 1.23388019,  2.01597855, -0.68176235, ..., -1.33182125,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 , -0.02240928, -0.0210444 , ..., -0.90975111,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.14197684, -1.01212132, ..., -0.34213954,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.94297153, -0.18622389, ..., -0.29847711,
        -0.47378505, -0.87137393]])

In [47]:
y =df["Outcome"].values

In [48]:
y


array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [49]:
from sklearn.model_selection import train_test_split
xtest,xtrain,ytest,ytrain = train_test_split(x,y,test_size=0.30,random_state=1)

In [50]:
# from here we start building Neural Network

import tensorflow as tf
from tensorflow.keras import Sequential # it is Used to build NN
from tensorflow.keras.layers import Dense # it is used to add layers
from sklearn.metrics import classification_report # Evaluation 

In [51]:
##Built a Model
#step 1-: init a model
ann=Sequential()
#step2-: add layers to model
ann.add(Dense(units=16,activation="relu")) #HL
ann.add(Dense(units=1,activation="sigmoid"))
#step3-: establish connection with layers
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
#step4-: fit the model
ann.fit(xtrain,ytrain,epochs=120,batch_size=32)
#step5-: make predictions
ypred=ann.predict(xtest)

Epoch 1/120
8/8 [==============================] - 1s 2ms/step - loss: 0.6019 - accuracy: 0.7359
Epoch 2/120
8/8 [==============================] - 0s 3ms/step - loss: 0.5865 - accuracy: 0.7446
Epoch 3/120
8/8 [==============================] - 0s 2ms/step - loss: 0.5726 - accuracy: 0.7619
Epoch 4/120
8/8 [==============================] - 0s 2ms/step - loss: 0.5600 - accuracy: 0.7619
Epoch 5/120
8/8 [==============================] - 0s 2ms/step - loss: 0.5486 - accuracy: 0.7706
Epoch 6/120
8/8 [==============================] - 0s 2ms/step - loss: 0.5374 - accuracy: 0.7749
Epoch 7/120
8/8 [==============================] - 0s 2ms/step - loss: 0.5276 - accuracy: 0.7792
Epoch 8/120
8/8 [==============================] - 0s 2ms/step - loss: 0.5178 - accuracy: 0.7792
Epoch 9/120
8/8 [==============================] - 0s 2ms/step - loss: 0.5091 - accuracy: 0.7749
Epoch 10/120
8/8 [==============================] - 0s 2ms/step - loss: 0.5014 - accuracy: 0.7792
Epoch 11/120
8/8 [===========

8/8 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8398
Epoch 85/120
8/8 [==============================] - 0s 2ms/step - loss: 0.3534 - accuracy: 0.8398
Epoch 86/120
8/8 [==============================] - 0s 2ms/step - loss: 0.3528 - accuracy: 0.8398
Epoch 87/120
8/8 [==============================] - 0s 2ms/step - loss: 0.3523 - accuracy: 0.8398
Epoch 88/120
8/8 [==============================] - 0s 2ms/step - loss: 0.3518 - accuracy: 0.8398
Epoch 89/120
8/8 [==============================] - 0s 2ms/step - loss: 0.3512 - accuracy: 0.8398
Epoch 90/120
8/8 [==============================] - 0s 2ms/step - loss: 0.3508 - accuracy: 0.8398
Epoch 91/120
8/8 [==============================] - 0s 2ms/step - loss: 0.3505 - accuracy: 0.8398
Epoch 92/120
8/8 [==============================] - 0s 2ms/step - loss: 0.3499 - accuracy: 0.8398
Epoch 93/120
8/8 [==============================] - 0s 2ms/step - loss: 0.3496 - accuracy: 0.8398
Epoch 94/120
8/8 [===============

In [52]:
ann.history.history

{}

In [25]:
ypred

array([[0.87258685],
       [0.06548584],
       [0.0408118 ],
       [0.34771973],
       [0.09564476],
       [0.6779749 ],
       [0.62471235],
       [0.45101506],
       [0.3218742 ],
       [0.28777075],
       [0.09244298],
       [0.04788144],
       [0.36637932],
       [0.16679803],
       [0.05011786],
       [0.33250266],
       [0.31535304],
       [0.04174338],
       [0.05484901],
       [0.19178309],
       [0.79674524],
       [0.04094164],
       [0.17379801],
       [0.07970993],
       [0.41151816],
       [0.33671933],
       [0.25224358],
       [0.39634642],
       [0.65787023],
       [0.7547584 ],
       [0.43043265],
       [0.24755257],
       [0.06775526],
       [0.14276864],
       [0.0149366 ],
       [0.0060863 ],
       [0.03524088],
       [0.0783173 ],
       [0.9672737 ],
       [0.39665204],
       [0.45875254],
       [0.03415519],
       [0.04076162],
       [0.3437164 ],
       [0.84938294],
       [0.2007321 ],
       [0.39765012],
       [0.024

In [26]:
#Step 6 Set a threshold
ypred = np.where(ypred>0.5,1,0)
ypred

array([[1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
    

In [27]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.79      0.85      0.82       354
           1       0.66      0.56      0.61       183

    accuracy                           0.75       537
   macro avg       0.72      0.71      0.71       537
weighted avg       0.74      0.75      0.75       537

